export { TimeRangeFormFieldComponent } from './lib/time-range-form-field.component'
export { timeRangeOrderValid } from './lib/validators/time-range-order'
export { timeRangeBounds } from './lib/validators/time-range-bounds'
export type { TimeRangeBounds } from './lib/validators/time-range-bounds'
export { timeRangeBothFilled } from './lib/validators/time-range-both-filled'
export { timeRangeWidth } from './lib/validators/time-range-width'
export type { TimeRangeWidthBounds } from './lib/validators/time-range-width'
export type { ITimeRange } from './lib/time-range.model'
export { TimeRangeErrorKind } from './lib/error-kinds'
