version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-*/*"
          - "@schematics/angular"
          - "zone.js"
      nx:
        patterns:
          - "@nx/*"
          - "nx"
          - "nx-cloud"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-*"
          - "ts-jest"
          - "@types/jest"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
