sudo: required
addons:
  chrome: stable
language: node_js
dist: trusty
node_js:
  - 16
branches:
  only:
    - main
    - /^merge-.*$/
    - /^deploy-.*$/
before_script:
  - npm install @angular/cli
  - npm install --legacy-peer-deps
script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build:ci
  - ng build --prod --base-href .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/playground/
  on:
    branch: main
