sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - 17
before_script:
  - npm install @angular/cli
  - npm install --legacy-peer-deps
  - npm install --save-dev @types/jest
script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build:ci
