sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - 17
before_script:
  - npm install pnpm
  - pnpm setup
  - pnpm install @angular/cli
  - pnpm install --legacy-peer-deps
  - pnpm install --save-dev @types/jest
script:
  - pnpm lint:ci
  - pnpm test:ci
  - pnpm build:ci
