export { PhoneFormFieldComponent } from './lib/phone-form-field.component'
export { phoneValid } from './lib/validators/phone-valid'
export { phonePossible } from './lib/validators/phone-possible'
export { phoneCountryIn } from './lib/validators/phone-country-in'
export { phoneTypeIn } from './lib/validators/phone-type-in'
export { getDefaultCountries } from './lib/countries/default-countries'
export { detectCountry } from './lib/locale/detect-country'
export type { IPhoneCountry } from './lib/phone.model'
export type { CountryCode, NumberType } from 'libphonenumber-js/max'
